### ISSUE TITLE
Cannot generate woff / woff2 font with node v10

### ISSUE THREAD

**Issue by itsmepetrov** [neoskop/ligscrib#1]
After updating to node v10 I've got the following error:

```
Write woff... Checksum error in glyf
```

Related issue: https://github.com/nfroidure/gulp-iconfont/issues/166

**Comment by draco-vetus** [comment]
I've updated the dependencies to fix the node 10 issue. Install the latest version (1.2.0) to use with node 10.

**Comment by itsmepetrov** [comment]
Thanks 👍
